[package]
name = "krusty_web"
version = "0.1.0"
authors = ["kevin", "steven"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
